### ISSUE TITLE
RoR group project: set up your Kanban board 

### ISSUE THREAD

**Issue by yash244466666** [yash244466666/Recipe-app-ROR#12]
### Hi, Code Reviewer 
**We are a group of two:** 

- @yash244466666 
- @Becky449 
-  This is the [link](https://github.com/users/yash244466666/projects/4) to our Kanban cards

**Comment by muneebulrehman** [comment]
Hi team, 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Great job including all the requirements on the board.

## Required Changes ♻️
_Check the comments under the review._

- [ ] The distribution of tasks is not fair. @yash244466666 has been allotted 4 individual tasks which sum to a total of 12 points whereas @Becky449 has been allotted 2 individual tasks which sum to a total of 5 points. Bear in mind that the maximum difference between the sums of your individual points should be <= 5. Kindly update your board accordingly and then submit for a re-review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
